controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (mySprite.isHittingTile(CollisionDirection.Bottom)) {
        mySprite.vy += -110
    }
})
let mySprite: Sprite = null
scene.setBackgroundImage(img`
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccfffffcccccccccccccccccccccccccccccccccccccccccccccccccccccccfffffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccffffffcccccccccccccccccccccccccccccccccccccccccccccccccccccccfffffffccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccfffffffffcccccccccccccccccccccccccccccccccccccccccccccccccccfffffffffffccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccffffffffffcccccccccccccccccccccccccccccccccccccccccccccccccfffffffffffffcccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccfffffffffffcccccccccccccccccccccccccccccccccccccccccccccccccffffffffffffffccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccffffffffffffccccccccccccccccccccccccccccccccccccccccccffccccffffffffffffffffcccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccfffffffffffffffccccccccccccccccccccccccccccccccccccccccccfccccfffffffffffffffffccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccffffffffffffffffccccccccccccccccffccccccccccccccccccccccccfccccffffffffffffffffffcccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccffffffffffffffffccccccccccccccccfffcccccccccccccccccccccccfcccfffffffffffffffffffffcccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccffffffffffffffffffccccccccccccccccffffcccccccccccccccccccccffccffffffffffffffffffffffccccccccccccccccccccccccccccfffffcccccccccccccc
    cccccccccccfcccccccccccccfcfffffffffffffffffffcccccccccccccccccfffccccccccccccccccccccccffffffffffffffffffffffffffcccccccccccccccccccccccccccfffffcccccccccccccc
    cccccccccccfccccccccccccfffffffffffffffffffffffccccccccccccccccccffccccccccccccccccccccfffffffffffffffffffffffffffffcccccccccccccccccccccccccffffffccccccccccccc
    bbbbbccccccffccccccccccfffffffffffffffffffffffffccccccccccccccccccffccccccccccccccccccfffffffffffffffffffffffffffffffcccccccccccccccccccccccfffffffccccccccccccc
    bbbbbcccccbfffbbbccccccffffffffffffffffffffffffffcccccccccccccccccffcccccccccccccccccffffffffffffffffffffffffffffffffffcccccccccccccccccccccfffffffccccccccccccc
    bbbbbccbbbbfbbfbbbbcccffffffffffffffffffffffffffffccccccccccccccccffccccccccccccccfffffffffffffffffffffffffffffffffffffcccccccccccccccccccccffffffffcccccccccccc
    bbbbbcbbbbbfbbffbbbbccfffffffffffffffffffffffffffffcccfcccccccccccfccccccccccccccccfffffffffffffffffffffffffffffffffffffffccccccccccccccccccffffffffcccccccccccc
    bbbbbbbbbbbffffffbbbbfffffffffffffffffffffffffffffffccfccccccccccffccccccccccccccccfffffffffffffffffffffffffffffffffffffffffccccccccccccccccffffffffcccccccccccc
    bbbbbbbbbbbbbbbbffbfffffffffffffffffffffffffffffffffffcccccccccccffcccccccccccccccfffffffffffffffffffffffffffffffffffffffffffccccccccccccccfffffffffcccccccccccc
    bbbbbbbbbbbbbbbbbfffffffffffffffffffffffffffffffffffffbbbbbcccccffccccccccccccccffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccffffffffffccccccccccc
    bbbbbbbbbbbbbbbbbbfffffffffffffffffffffffffffffffffffffffffbcccfffcccccccccccccfffffffffffffffffffffffffffffffffffffffffffffffccccccccccccffffffffffffcccccccccc
    bbbbbbbbbbbbbbbbbffffffffffffffffffffffffffffffffffffffffffffccfffcccccccfccccffffffffffffffffffffffffffffffffffffffffffffffffccccccccccccffffffffffffcccccccccc
    bbbbbbbbbbfbbbbbffffffffffffffffffffffffffffffffffffffffffffffcffcccccccfcccccffffffffffffffffffffffffffffffffffffffffffffffffccccccccccccfffffffffffffccccccccc
    bbbbbbbbbbfffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccffffffffffffffffffffffffffffffffffffffffffffffffbccccccccccfffffffffffffffcccccccc
    bbbbbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbccbbbbffffffffffffffffffffffffffffffffffffffffffffffffbbbbbccccccffffffffffffffffccccccc
    bbbbbbbbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbbbcfffffffffffffffffccccccc
    bbbbbbbbbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbbbbffffffffffffffffffccccccc
    bbbbfbbbbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbbbffffffffffffffffffffffffffffffffffffffffffffffbbbbbffbffffffffffffffffffffccccccc
    bbbbfbbbbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbbbbfffffffffffffffffffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffcccccc
    bbbbfbbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbbbbbbfffffffffffffffffffffffffffffffffffffffffbbbbffbfbffffffffffffffffffffffffccccc
    bbbbfffbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbbbbbbfffffffffffffffffffffffffffffffffffffffbbbbbffbfbbfffffffffffffffffffffffffcccc
    bbbbbbfbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbbbbbbffffffffffffffffffffffffffffffffffffffffffffbbfbbffffffffffffffffffffffffffcccc
    bbbbbbbfbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbbbbbbbbbffffffffffffffffffffffffffffffffffffbbffbbbffbbffffffffffffffffffffffffffcccc
    bbbbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbffbbbbbbbbbbffffffffffffffffffffffffffffffffffffbbbbffffbbbfffffffffffffffffffffffffffbbb
    bbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbffbbbbbbbbbbbffffffffffffffffffffffffffffffffffffbbbbbbbbbbbffffffffffffffffffffffffffffbb
    bbbbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffbbbbbbbbbbbbbfffffffffffffffffffffffffffffffffffbbbbbbbbbbbfffffffffffffffffffffffffffffb
    bbbbbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbfffbbbbbbbbbbbbbbffffffffffffffffffffffffffffffffffbbbbbbbbbbfffffffffffffffffffffffffffffff
    bbbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffbbffffbbbbbbbbbbbbbbbbffffffffffffffffffffffffffffffffffbbbbbbbbbbfffffffffffffffffffffffffffffff
    bbbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffbbbbbbbbbbbbbbbbbbfffffffffffffffffffffffffffffffffbbbbbbbbbbfffffffffffffffffffffffffffffff
    bbbbbbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbffffffffffffffffffffffffffffffffbbbbbbbbbbffffffffffffffffffffffffffffffff
    bbbbbbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbbbbbbffbbbbbbbbbbbbffffffffffffffffffffffffffffbbbbbbbbbbfffffffffffffffffffffffffffffffff
    bbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbbbbbbfbfbbbbbbbbbbbfffffffffffffffffffffffffffbbbbbbbbbbffffffffffffffffffffffffffffffffff
    bbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbbbbbfffffbbbbbbbbbbbbbffffffffffffffbbbbfffffbbbbbbbbbbfffffffffffffffffffffffffffffffffff
    bbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbfbbbffffffbbbbbbbbbbbbbfffffffffffffbbbbbbbbbbbbbbfbbbbfffffffffffffffffffffffffffffffffff
    bbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbfbbbfffffffbbbbbbbbbbbbfffffffffffffbbbbbbbbbbbbbbffbfffffffffffffffffffffffffffffffffffff
    bbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbbfbfffffffffbbbbbbbbbbbfffffffffffffbbbbbbbbbbbbbbbfffffffffffffffffffffffffffffffffffffff
    bbbbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbbfffffffffffbbffbbbbbbbfffffffffffffbbbbbbbbbbbbbbbfffffffffffffffffffffffffffffffffffffff
    bbbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbbfffffffffffbbffbbbbbbbffffffffffffffbbbbbbbbbbbbbffffffffffffffffffffffffffffffffffffffff
    bbbbbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbfbfffffffffffffffbbbbbbbbffffffffffffffbbbbbbbbbbbbbffffffffffffffffffffffffffffffffffffffff
    bbbbbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbfffffffffffffffffbbbbbbbbffffffffffffffbbbbbbbbbbbbbffffffffffffffffffffffffffffffffffffffff
    bbbbbbbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbffffffffffffffffbbbbbbbfbbffffffffffffffbbbbbbbbbbbbbffffffffffffffffffffffffffffffffffffffff
    bbbbbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbffffffffffffffffbbbbbbffbbffffffffffffffbbbbbbbbbbbbbffffffffffffffffffffffffffffffffffffffff
    bbbbbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbfffffffffffffffffbbfffffbbffffffffffffffbbbbbbbbbbbbbffffffffffffffffffffffffffffffffffffffff
    bbbbbbbbbbffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbfffffffffffffffffffffffbbbbfffffffffffffbbbbbbbbbbbbbbffffffffffffffffffffffffffffffffffffffff
    bbbbbbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbfffffffffffffffffffbbbbbbbbfffffffffffffbbbbbbbbbbbbbbffffffffffffffffffffffffffffffffffffffff
    bbbbbbbbbbbbffffffffffffffffffffffffffffffffffffffffffffffffbbffbffffffffffffffffffffbbbbbbbbfffffffffffffbbbbbbbbbbbbbbffffffffffffffffffffffffffffffffffffffff
    bbbbbbbbbbbbbbfffffffffffffffffffffffffffffffffffffffffffffbbbffbffffffffffffffffffffbbbbbbbbfffffffffffffbbbbbbbbbbbbbbffffffffffffffffffffffffffffffffffffffff
    bbbbbbbbbbbbbbbffffffffffffffffffffffffffffffffffffffffffffbbbbffffffffffffffffffffffbbbbbbbbfffffffffffffbbbbbbbbbbbbbbffffffffffffffffffffffffffffffffffffffff
    bbbbbbbbbbfbbbbffffffffffffffffffffffffffffffffffffffffffbbbbbbbfffffffffffffffffffffffbbbbbbfffffffffffffbbbbbbbbbbbbbbbfffffffffffffffffffffffffffffffffffffff
    bbbbbbbbbbffbbbbfffffffffffffffffffffffffffffffffffffffbbbbbbbbffffffffffffffffffffffffffbbbbfffffffffffffbbbbbbbbbbbbbbbbffffffffffffffffffffffffffffffffffffff
    bbbbbbbbbbbfbbbbffffffffffffffffffffffffffffffffffffbbbbbbbbbbfffffffffffffffffffffffffffbbbbfffffffffffffbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffffffffffffffffffff
    bbbbbbbbbbbbfbbbffffffffffffffffffffffffffffffffffbbbbbbbffffffffffffffffffffffffffffffffffbbbfffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffffffffffffffffff
    bbbbbbbbbbbbffbbfffffffffffffffffffffffffffffffffbbbbbbbbbbffffffffffffffffffffffffffffffffbbbfffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbffffffffffffffffffffffffffff
    bbbbbbbbbbbbbfffffffffffffffffffffffffffffffffffbbbbbbbbbbbffffffffffffffffffffffffffffffffbbfffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffffffffffffffff
    bbbbbbbbbbbbbbffffffffffffffffffffffffffffffffbbbbbbbbbbbbfffffffffffffffffffffffffffffffffbbffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffffffffffffffb
    bbbbbbbbbbbbbbbffffffffffffffffffffffffbbbbbbbbbbbbbbbbbbbfffffffffffffffffffffffffffffffffbbfffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffffffffffffbb
    bbbbbbbbbbbbbbbffffffffffffffffffffffffbbbbbbbbbbbfffbbbbbffffffffffffffffffffffffffffffffbbbffffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffffffffffbb
    bbbbbbbbbbbbbbbffffffffffffffffffffffffbbbbbbbbbbbbbbfbbbbffffffffffffffffffffffffffffffffbbbfffffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbffffffffffffbbbbbbbbbb
    bbbbbbbbbbbbbbbffffffffffffffffffffffffbbbbbbbbbbbbbbfffbbffffffffffffffffffffffffffffffffbbbffffffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbffffffffffbbbbbbbbbb
    bbbbbbbbbbbbbbbbfffffffffffffffffffffffbbbbbbbbbbbbbbbbbfbffffffffffffffffffffffffffffffffbbfffffffffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbffffffffffbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbffffffffffffffffbbbbbbbbbbbbbbbbbbffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbffffffffffffffbbbbbbbbbbbbbbbbbbbbbfffffffffffffffffffffffffffffffffbffffffffffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbfffffffffffffbbbbbbbbbbbbbbbbbbbbbbfffffffffffffffffffffffffffffffbbffffffffffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbfffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbffffffffffffffffffffffffffffbbbffffffffffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbffffffffffffffffffffffffffbbbbffffffffffffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbfffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffffbbbbbbbbbbbbbbffffffffffffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbfffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbffffffffffffffbbbbbbbbbbbbbffffffffffffffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbffffffffffffbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbfffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffffffffffbbbbbbbbbbbbffffffffffffffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbffffffffffffbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbfffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffbbbbbbbbbbbfffffffffffffffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbffffffffffffbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbfffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffffffffffffbbbbbbbbbbbfffffffffffffffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbffffffffffffbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbfffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffffffffffffbbbbbbbbbbbfffffffffffffffffffffffffffffbfffbbbbbfbbbbbbbbbbbbffffffffffffbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbfffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffffffffffffbbbbbbbbbbbfffffffffffffffffffffffffffffbffffbbbbfbbbbbbbbbbbbffffffffffffbbbbbbbb
    bffffbbbbbbbbbbbbbbbbbbbfffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffbbbbbbbbbbbffffffffffffffffffffffffffffbfffffbbffbbbbbbbbbbbbffffffffffffbbbbbbbb
    bbffffbbbbbbbfbbbbbbbbbffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffffffffffffffbbbbbbbbbbbfffffffffffffffffffffffffffffffffbbffbbbbbbbbbbbbfffffffffffffbbbbbbb
    bbfffffbbbbbbfbbbbbbbbbffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffffffffffffffbbbbbbbfbbbfffffffffffffffffffffffffffffffffbffffbbbbbbbbfbbfffffffffffffbbbbbbb
    bbffffffbbbbbfbbbbbbbbbffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffffffffffffffbbbbbbbffbbbfffffffffffffffffffffffffffffffffffffbbbbbbbbffffffffffffffffbbbbbbb
    bbbfffffbbbbffbbbbfbbbfffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffffbbbbbbffffbbbffffffffffffffffffffffffffffffffffffbbbbbbbbbfffffffffffffffbbbbbbb
    bbbfffffffffffbbbfffbbfffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffffbbbbbbfffffbbffffffffffffffffffffffffffffffffffffbbbbffbbbfffffffffffffffbbbbbbb
    bbbffffffffffffffffffbfffffffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffffbbbbbbfffffffffffffffffffffffffffffffffffffffffffbbbbfffbbfffffffffffffffbbbbbbb
    fffffffffffffffffffffffffffffffffffffbbbbbbbbbbbbbbfbbbbbbbbbbbbbfffffffffffffffbbbbfffffffffffffffffffffffffffffffffffffffffffffbbbbbfffffffffffffffffffbbbbbbb
    fffffffffffffffffffffffffffffffffffffbbfbbbbbbbbbbbfbbbbbbbbbbbfbfffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffbbbbbbfffffffffffffffffffbbbbbbb
    fffffffffffffffffffffffffffffffffffffffffbbbbbbbbbbfffbbbbbbbbbfbfffffffffffffffbbffffffffffffffffffffffffffffffffffffffffffffffbbfbbbfffffffffffffffffffbbbbbbb
    ffffffffffffffffffffffffffffffffffffffffffbfffbbffffffbbbbbbffbfbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbffbbffffffffffffffffffffbbbbbb
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffbbbbbb
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbb
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffbbb
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffb
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    `)
game.splash("escape the hollowgast")
mySprite = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . f f f f . . . . . . . 
    . . . . . f d d f f . . . . . . 
    . . . . . d f d f d . . . . . . 
    . . . . . d d d d d . . . . . . 
    . . . . . d d d d d . . . . . . 
    . . . . . e 8 8 8 e . . . . . . 
    . . . . . e e 8 e e . . . . . . 
    . . . . . e e e e e . . . . . . 
    . . . . . e f f f e . . . . . . 
    . . . . . d f f f d . . . . . . 
    . . . . . . f f f . . . . . . . 
    . . . . . . f f f . . . . . . . 
    `, SpriteKind.Player)
mySprite.ay = 120
controller.player1.moveSprite(mySprite, 100, controller.dy())
scene.cameraFollowSprite(mySprite)
tiles.setCurrentTilemap(tilemap`level4`)
music.play(music.createSong(hex`0078000408020106001c00010a006400f401640000040000000000000000000000000000000002730000000400041d20242904000800011b08000c0002252c0c001000031d22291000140002192914001800012418001c00021d201c0020000319252c20002400011e240028000319272a28002c00021b222c003000021e2230003400011934003800031b252938003c000319222c3c004000021925`), music.PlaybackMode.LoopingInBackground)
